"""Record ESPN page fixtures and expected-output snapshots for the offline tests.

Run this when ESPN intentionally changes its page format and the offline
fixtures need to be refreshed:

    python tests/record_fixtures.py                  # re-record pages + snapshots
    python tests/record_fixtures.py --pages-only     # refresh pages, keep snapshots
    python tests/record_fixtures.py --snapshots-only # rebuild snapshots from saved pages

After recording, review `git diff --stat tests/fixtures/` and spot-check
snapshot values before committing — the snapshots are regenerated by running
the scraper against the just-recorded pages, so they will always match the
current code; the human review is what protects against snapshotting broken
parsing.
"""

import argparse
import gzip
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from curl_cffi import requests

sys.path.insert(0, str(Path(__file__).parent))
from conftest import (  # noqa: E402
    FIXTURE_DIR,
    PAGES_DIR,
    PLAYERS,
    SCHEDULES,
    SCOREBOARD_DATES,
    SNAPSHOT_DIR,
    STATIC_GAMES,
    FakeResponse,
    FixtureStore,
    SerialParallel,
)

from cbbpy import mens_scraper as ms, womens_scraper as ws  # noqa: E402
from cbbpy.utils import cbbpy_utils as cu  # noqa: E402
from cbbpy.utils import espn_api as api  # noqa: E402


URLS = {
    "mens": {
        "scoreboard": cu.MENS_SCOREBOARD_URL,
        "game": cu.MENS_GAME_URL,
        "boxscore": cu.MENS_BOXSCORE_URL,
        "pbp": cu.MENS_PBP_URL,
        "player": cu.MENS_PLAYER_URL,
        "schedule": cu.MENS_SCHEDULE_URL,
    },
    "womens": {
        "scoreboard": cu.WOMENS_SCOREBOARD_URL,
        "game": cu.WOMENS_GAME_URL,
        "boxscore": cu.WOMENS_BOXSCORE_URL,
        "pbp": cu.WOMENS_PBP_URL,
        "player": cu.WOMENS_PLAYER_URL,
        "schedule": cu.WOMENS_SCHEDULE_URL,
    },
}

SCRAPERS = {"mens": ms, "womens": ws}


def fetch(url):
    header = {"Referer": str(np.random.choice(cu.REFERERS))}
    resp = requests.get(url, headers=header, impersonate="chrome")
    resp.raise_for_status()
    if cu.WINDOW_STRING.encode() not in resp.content:
        raise RuntimeError(
            f"Fetched page has no {cu.WINDOW_STRING!r} payload (WAF challenge or "
            f"format change?): {url} -> HTTP {resp.status_code}, {len(resp.content)} bytes"
        )
    time.sleep(np.random.uniform(low=1, high=2))
    return resp.content


def record_pages():
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    manifest = {}

    def save(label, url):
        fname = f"{label}.html.gz"
        print(f"  {label} <- {url}")
        (PAGES_DIR / fname).write_bytes(gzip.compress(fetch(url)))
        manifest[url] = {
            "file": fname,
            "recorded_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        }

    all_games = {}
    for gender in ("mens", "womens"):
        print(f"Recording {gender} pages...")
        urls = URLS[gender]

        date = datetime.strptime(SCOREBOARD_DATES[gender], "%Y-%m-%d")
        d = date.strftime("%Y%m%d")
        save(f"{gender}_scoreboard_{d}", urls["scoreboard"].format(d))

        # discover that date's game ids from the page just recorded, using the
        # library's own parser
        from bs4 import BeautifulSoup

        page = gzip.decompress((PAGES_DIR / f"{gender}_scoreboard_{d}.html.gz").read_bytes())
        scoreboard = cu._get_scoreboard_from_soup(BeautifulSoup(page, "lxml"))
        scoreboard_games = [str(x["id"]) for x in scoreboard]
        print(f"  scoreboard games on {SCOREBOARD_DATES[gender]}: {scoreboard_games}")

        games = STATIC_GAMES[gender] + [g for g in scoreboard_games if g not in STATIC_GAMES[gender]]
        all_games[gender] = games

        for gid in games:
            save(f"{gender}_game_{gid}", urls["game"].format(gid))
            save(f"{gender}_boxscore_{gid}", urls["boxscore"].format(gid))
            save(f"{gender}_pbp_{gid}", urls["pbp"].format(gid))

        for pid in PLAYERS[gender]:
            save(f"{gender}_player_{pid}", urls["player"].format(pid))

        for season, team in SCHEDULES[gender]:
            team_id, _ = cu._get_id_from_team(team, season, gender)
            save(f"{gender}_schedule_{team_id}_{season}", urls["schedule"].format(team_id, season))

    (FIXTURE_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (FIXTURE_DIR / "games.json").write_text(json.dumps(all_games, indent=2) + "\n")
    print(f"Wrote {len(manifest)} pages + manifest.json")


def fetch_json(url, required_key):
    header = {"Referer": str(np.random.choice(cu.REFERERS))}
    resp = requests.get(url, headers=header, impersonate="chrome")
    resp.raise_for_status()
    if required_key.encode() not in resp.content:
        raise RuntimeError(
            f"Fetched JSON has no {required_key!r} key (format change?): {url} -> "
            f"HTTP {resp.status_code}, {len(resp.content)} bytes"
        )
    time.sleep(np.random.uniform(low=1, high=2))
    return resp.content


def record_api():
    """Record ESPN JSON API summary + scoreboard responses, merged into the manifest.

    Reuses the same game ids and scoreboard dates as the HTML fixtures so the two
    sources are recorded for identical games (see the parity test).
    """
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    manifest = json.loads((FIXTURE_DIR / "manifest.json").read_text())
    games = json.loads((FIXTURE_DIR / "games.json").read_text())

    def save(label, url, required_key):
        fname = f"{label}.json.gz"
        print(f"  {label} <- {url}")
        (PAGES_DIR / fname).write_bytes(gzip.compress(fetch_json(url, required_key)))
        manifest[url] = {
            "file": fname,
            "recorded_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        }

    for gender in ("mens", "womens"):
        print(f"Recording {gender} API responses...")
        summary_url = (
            api.MENS_API_SUMMARY_URL if gender == "mens" else api.WOMENS_API_SUMMARY_URL
        )
        scoreboard_url = (
            api.MENS_API_SCOREBOARD_URL
            if gender == "mens"
            else api.WOMENS_API_SCOREBOARD_URL
        )

        for gid in games[gender]:
            save(f"{gender}_api_summary_{gid}", summary_url.format(gid), "header")

        d = datetime.strptime(SCOREBOARD_DATES[gender], "%Y-%m-%d").strftime("%Y%m%d")
        save(f"{gender}_api_scoreboard_{d}", scoreboard_url.format(d), "events")

    (FIXTURE_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print("Merged API responses into manifest.json")


def replay_offline():
    """Point the scraper at the recorded pages (same patches as the offline_espn fixture)."""
    store = FixtureStore(FIXTURE_DIR)
    cu.r.get = lambda url, *a, **kw: FakeResponse(store.get(url))
    cu.time.sleep = lambda *_: None
    cu.ATTEMPTS = 1
    cu.Parallel = SerialParallel
    return store


def build_snapshots():
    SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
    games = json.loads((FIXTURE_DIR / "games.json").read_text())
    store = replay_offline()

    def save(df, name):
        assert len(df) > 0, f"snapshot {name} came back empty"
        df.to_parquet(SNAPSHOT_DIR / f"{name}.parquet")
        print(f"  {name}.parquet: {len(df)} rows x {len(df.columns)} cols")

    for gender in ("mens", "womens"):
        print(f"Building {gender} snapshots...")
        sc = SCRAPERS[gender]

        info = pd.concat([sc.get_game_info(g, source="html") for g in games[gender]], ignore_index=True)
        box = pd.concat([sc.get_game_boxscore(g, source="html") for g in games[gender]], ignore_index=True)
        pbp = pd.concat([sc.get_game_pbp(g, source="html") for g in games[gender]], ignore_index=True)
        save(info, f"{gender}_game_info")
        save(box, f"{gender}_game_boxscore")
        save(pbp, f"{gender}_game_pbp")

        players = pd.concat([sc.get_player_info(p) for p in PLAYERS[gender]], ignore_index=True)
        save(players, f"{gender}_player")

        sched = pd.concat(
            [sc.get_team_schedule(team, season) for season, team in SCHEDULES[gender]],
            ignore_index=True,
        )
        save(sched, f"{gender}_team_schedule")

        d = SCOREBOARD_DATES[gender]
        r_info, r_box, r_pbp = sc.get_games_range(d, d, source="html")
        save(r_info, f"{gender}_range_info")
        save(r_box, f"{gender}_range_boxscore")
        save(r_pbp, f"{gender}_range_pbp")

        # sanity guards: the recorded set must keep covering its edge cases
        assert (info.num_ots >= 1).any(), f"{gender}: no OT game in recorded set"
        assert info.is_postseason.any(), f"{gender}: no postseason game in recorded set"
        if gender == "womens":
            halves_pbp = sc.get_game_pbp("303442739")
            assert "half" in halves_pbp.columns and "quarter" not in halves_pbp.columns, (
                "womens pre-2015 game no longer parses as halves-based"
            )

    assert not store.misses, f"snapshot build requested unrecorded URLs: {store.misses}"
    print("Snapshots built. Review `git diff --stat tests/fixtures/` before committing.")


def build_api_snapshots():
    """Rebuild the API-path snapshots (separate files from the HTML snapshots).

    Both sources share most columns; the API path additionally populates
    player_id/assist_player_id/shot coordinates and the odds columns
    (home_point_spread/over_under/home_moneyline/away_moneyline) that the archived
    HTML embed leaves empty, so the two snapshot sets legitimately differ on those
    columns (see the parity test's exclusion list).
    """
    SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
    games = json.loads((FIXTURE_DIR / "games.json").read_text())
    store = replay_offline()

    def save(df, name):
        assert len(df) > 0, f"snapshot {name} came back empty"
        df.to_parquet(SNAPSHOT_DIR / f"{name}.parquet")
        print(f"  {name}.parquet: {len(df)} rows x {len(df.columns)} cols")

    for gender in ("mens", "womens"):
        print(f"Building {gender} API snapshots...")
        sc = SCRAPERS[gender]

        # source defaults to "api"
        info = pd.concat([sc.get_game_info(g) for g in games[gender]], ignore_index=True)
        box = pd.concat([sc.get_game_boxscore(g) for g in games[gender]], ignore_index=True)
        pbp = pd.concat([sc.get_game_pbp(g) for g in games[gender]], ignore_index=True)
        save(info, f"{gender}_game_info_api")
        save(box, f"{gender}_game_boxscore_api")
        save(pbp, f"{gender}_game_pbp_api")

        d = SCOREBOARD_DATES[gender]
        r_info, r_box, r_pbp = sc.get_games_range(d, d)
        save(r_info, f"{gender}_range_info_api")
        save(r_box, f"{gender}_range_boxscore_api")
        save(r_pbp, f"{gender}_range_pbp_api")

    assert not store.misses, f"API snapshot build requested unrecorded URLs: {store.misses}"
    print("API snapshots built. Review `git diff --stat tests/fixtures/` before committing.")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    group = ap.add_mutually_exclusive_group()
    group.add_argument("--pages-only", action="store_true", help="refresh pages, keep snapshots")
    group.add_argument("--snapshots-only", action="store_true", help="rebuild snapshots from saved pages")
    group.add_argument("--api-only", action="store_true", help="record only API responses + build API snapshots")
    args = ap.parse_args()

    if args.api_only:
        record_api()
        build_api_snapshots()
    else:
        if not args.snapshots_only:
            record_pages()
            record_api()
        if not args.pages_only:
            build_snapshots()
            build_api_snapshots()
